- baseInfo:
    api_name: 商品详情
    url: /coupApply/cms/productDetail
    method: post
    header:
      Content-Type': application/json;charset=UTF-8
  testCase:
    - case_name: 获取商品详情信息
      json:
        pro_id: ${get_extract_data_list(goodsid, 2)}  # 随机获取一个商品 ID
        page: 1
        size: 20
      validation:
        - contains: {'error_code': '0000'}